--------------------------------------------------------
--
-- This deviates from the other vendors - I've taken out all grants
--  here.  Grants should be done when necessary, not globally on
--  all tables by default.  - JO
--
--------------------------------------------------------
